### ISSUE TITLE
pyvista visualization

### ISSUE THREAD

**Issue by max-hassani** [pyiron/pyiron_continuum#112]
Both fenics and damask can export their output to vtk files. We can use pyvista in pyiron_continuum to have interactive visualizations based on the data (stress, strain, temperature, etc) or timesteps. Such visaulization can be found in [here](https://github.com/muh-hassani/precice_workshop/blob/master/fenics_precice_heat_conduction.ipynb), at the end of the notebook.

**Comment by samwaseda** [comment]
Silently introduced in [this PR](https://github.com/pyiron/pyiron_continuum/pull/287)
