### ISSUE TITLE
`run_rolling` in damask should be just `run`

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_continuum#174]
cf. title

**Comment by yangbai90** [comment]
Hi @samwaseda , is it possible to rewrite or and new function in the subclass.run() call. The reason to use run_rolling instead of job.run() itself is that, we want to have some specific function in run_rolling().

**Comment by samwaseda** [comment]
Yes, we have to define `run_static`, but I guess I can take over the task.
