### ISSUE TITLE
[Damask] Stress-strain goes beyond yield stress?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_continuum#258]
![Unknown](https://github.com/pyiron/pyiron_continuum/assets/37879103/5f0c9d42-c733-4b0c-979e-688aaeef44ab)

I just ran [this notebook](https://github.com/pyiron/pyiron_continuum/blob/main/notebooks/damask_tutorial.ipynb) and realized that the zz-component of the stress apparently goes beyond the yield stress. Is that what is supposed to happen?

**Comment by yangbai90** [comment]
Hi @samwaseda , I think the result is correct. Here the figure shows the sigma_zz vs strain_zz plot, while the RVE is subjected to the loading along x-axis. If you check the vonMises stress vs vonMises strain plot, the magnitude of the stress (10^8 Pa) is much higher than this figure (-8000~6000 Pa).

**Comment by samwaseda** [comment]
ok but is it appropriate as an example? Shouldn't it be replaced by the xx-direction?

**Comment by yangbai90** [comment]
> ok but is it appropriate as an example? Shouldn't it be replaced by the xx-direction?

I believe this is acceptable; the two figures serve to showcase the functionality of 1) the zz, xx, or yy plot, and 2) the vonMises stress versus strain plot. Therefore, we should retain the zz plot.
