### ISSUE TITLE
Requiring notebooks tests and env fulfillment 

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_continuum#319]
@samwaseda and @mbruns91, after approval I merged https://github.com/pyiron/pyiron_continuum/pull/317, which had all tests passing. Unfortunately, both Sam and I failed to remember to run the notebook tests, and these [failed](https://github.com/pyiron/pyiron_continuum/actions/runs/9340641264/job/25706435243) when they ran on merge.

Since these tests are quite expensive, I understand the rationale for having them only run when the label is applied -- one doesn't necessarily want to burn compute running them on every commit. However, since it's far to easy to forget them, I've now added the a requirement the the `main` protection rules that this test be passing before merging is allowed.

I've got a patching PR here that adds the dependency to the other env file, and it looks like it's blocking things correctly as the test is running and the merge button is deactivated for me citing the rule.

1) Are you ok with this rule? It's a matter of a couple clicks to turn it off, so I turned it on unilaterally
2) @samwaseda and I already missed one env location... can someone double check we didn't make further mistakes in the dependency handling in #317?

**Comment by samwaseda** [comment]
I'm fine with the rule, but do integration tests (which I think are what you are talking about?) [don't get triggered when the `integration` label is simply added](https://github.com/pyiron/pyiron_continuum/issues/311)? If they get triggered, I'm fine with it.

**Comment by samwaseda** [comment]
Since we talked about this in the pyiron meeting yesterday and the problem I mentioned above got resolved, I close this issue.
