### ISSUE TITLE
ModuleNotFoundError for `import fenics as FEN`

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_continuum#64]
https://github.com/pyiron/pyiron_continuum/blob/cbc7c08419550ba49275bbc234f6bbe590c8de0f/pyiron_continuum/fenics/job/generic.py#L9

I get a `ModuleNotFoundError` for `import fenics as FEN` when I try to import `pyiron_continuum`

**Comment by liamhuber** [comment]
Although it's tangential to what he was doing, this is now addressed by Muhammad over in #63. Once that's merged you should be good to go.

I still want to dig a little bit into how to centralize the alarm, and we need to look at convenient ways to document alarmed stuff, but it's lower priority for me.

**Comment by muh-hassani** [comment]
I guess, it is not an issue anymore with the importalarms, we have. @samwaseda @liamhuber
