### ISSUE TITLE
Towards the continuum scale 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron_continuum#7]
As part of the [Simulation Workflows in Materials Modelling (SWiMM 2021) Workshop](https://www.cecam.org/workshop-details/27) [precice](https://www.precice.org) is presented as a tool to couple [fenics](https://fenicsproject.org) and [openfoam](https://openfoam.org) so that might be an interesting extension for pyiron as well. The precice tutorials takes place next week Wednesday March 24th to 26th 2021 - three sessions with 45 minutes each. The workshop registration is still open in case that is interesting for you @muh-hassani , @Ahmed-Aslam  and @liamhuber .

**Comment by Ahmed-Aslam** [comment]
Thank you @jan-janssen.

**Comment by muh-hassani** [comment]
thanks @jan-janssen. If I can register, I will take part in it definitely.

**Comment by liamhuber** [comment]
This month is already pretty packed for me, but I appreciate the heads-up!
